year = '2024'
state = 'Andaman and Nicobar'
district = 'Port Blair'
# establishment = 'District and Sessions Judge, Port Blair, Andaman'
establishment = 'Civil Judge Sr Divn, Port Blair, Andaman'
case = 'Civil Suit  27  2024'
